### ISSUE TITLE
TIM的demo测试问题，TIM_calculateValue()函数计算结果溢出

### ISSUE THREAD

**Issue by breakeryu** [MCU-ZHISHAN-IoT/HML_FwLib_STC89#2]
你们好！
       我现在测试tim的example，发现了一些问题。具体的问题在于TIM_calculate()计算的结果出错，没有正确的返回我设置的值！我在附件中会放上我测试的代码。
       另外的一件事，这个TIM的demo中也有一些问题，在定时器中断函数中，很明显没有重装载定时器TH、TL。我想问一下这个是不是有一些我没有搞懂的地方？还是这是属于demo中的BUG？
       请make文档usr中的test文件。我使用的就是你们开源的HML工程。如果有其他的需要我提供的，我可以再进行补充。
[HML_FwLib_STC89_2021.zip](https://github.com/MCU-ZHISHAN-IoT/HML_FwLib_STC89/files/5926003/HML_FwLib_STC89_2021.zip)

**Comment by breakeryu** [comment]
问题补充图片：issue1的图片显示test.c运行之后，我这边的串口显示的数据。

从后面的时间戳上面可以看到这个定时器的时间准确度是可以接受的，但是如果把定时器中断函数中的重装载语句 `TIM_setValue(PERIPH_TIM_0,60536);`去掉，也就是example中展示的，很显然这样的定时器是工作不正常的。

![issue1](https://user-images.githubusercontent.com/35825642/106900367-66c24c00-6731-11eb-9d8c-07f237ac0884.png)

**Comment by breakeryu** [comment]
现在通过一些测试，我发现是定义的uint16在我的编译环境下，最后运行的结果是int16。换句话说，这里的uint16数据类型，预计的范围应当是0-65535，但是表现出来的却是--32768 ~ 32767。这让我很头疼。。

**Comment by breakeryu** [comment]
经过一些测试，经过重定向的prinrf的问题打印输出的结果是有问题的。printf("%d",12345）;和printf("%u",12345);结果是不同的。姑且我先不使用printf吧。我现在的目标是测试tim。这个printf使我偏离了我原来的目标。

**Comment by zsiothsu** [comment]
你好，谢谢帮忙测试！经过我的测试后发现: sdcc 编译器所用的标准库中，`printf` 及其变种最高支持16位的整型输出，所以会产生问题描述的情况

如以下语句:
```c
	printf_small("%d\r\n",0xFFFFFUL);
```
产生的汇编代码为
```asm
	mov	a,#0xff
	push	acc
	push	acc
	mov	a,#0x0f
	push	acc
	clr	a
	push	acc ;这边0xFFFFFUL是作为32位传入的
	mov	a,#___str_1
	push	acc
	mov	a,#(___str_1 >> 8)
	push	acc
	mov	a,#0x80
	push	acc
	lcall	_printf_small
	mov	a,sp
	add	a,#0xf9
	mov	sp,a

	;other code

___str_1:
	.ascii "%d"
	.db 0x0d
	.db 0x0a
	.db 0x00
	.area CSEG    (CODE)
	.area CONST   (CODE)
```

实例中传入 `printf` 的为一个 20 位的数据 `0xFFFFF`，经过编译后是作为 32 位数据 `0x000FFFFF` 传入的，由于只支持最大 16 位，`printf`把高16位的数据作为 `%d` 的值，所以最终打印的数据为

```
15
```

如果是如下语句
```c
	//0xEC78 为 TIM_calculateValue(5000, TIM_mode_1) 的结果 
	printf_small("%d\r\n",(uint16_t)0xEC78);
```

编译结果为

```asm
	mov	a,#0x78
	push	acc
	mov	a,#0xec
	push	acc ;注意这边只push了16位（2个acc）
	mov	a,#___str_1
	push	acc
	mov	a,#(___str_1 >> 8)
	push	acc
	mov	a,#0x80
	push	acc
	lcall	_printf_small
	mov	a,sp
	add	a,#0xfb
	mov	sp,a
```

16的值（0xEC78）最高位为 1，打印结果为
```
-5000
```

所以要打印结果的话，可以使用 `printf("%u",...) `（占用空间较大） 或者直接传送16位数据到电脑

**Comment by breakeryu** [comment]
好的，我们能不能进行这方面的改进，使用部分汇编语言进行一些改善printf的函数，修改这个BUG呢？或者自定义一个中间件printf函数。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chipen Hsiao"<notifications@github.com&gt;; 
发送时间: 2021年2月18日(星期四) 晚上8:43
收件人: "MCU-ZHISHAN-IoT/HML_FwLib_STC89"<HML_FwLib_STC89@noreply.github.com&gt;; 
抄送: "鱼"<1399634553@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MCU-ZHISHAN-IoT/HML_FwLib_STC89] TIM的demo测试问题，TIM_calculateValue()函数计算结果溢出 (#2)





 
你好，谢谢帮忙测试！经过我的测试后发现: sdcc 编译器所用的标准库中，printf 及其变种最高支持16位的整型输出，所以会产生问题描述的情况
 
如以下语句:
 	printf_small("%d\r\n",0xFFFFFUL);
 
产生的汇编代码为
 	mov	a,#0xff 	push	acc 	push	acc 	mov	a,#0x0f 	push	acc 	clr	a 	push	acc ;这边0xFFFFFUL是作为32位传入的 	mov	a,#___str_1 	push	acc 	mov	a,#(___str_1 &gt;&gt; 8) 	push	acc 	mov	a,#0x80 	push	acc 	lcall	_printf_small 	mov	a,sp 	add	a,#0xf9 	mov	sp,a 	;other code ___str_1: 	.ascii "%d" 	.db 0x0d 	.db 0x0a 	.db 0x00 	.area CSEG    (CODE) 	.area CONST   (CODE)
 
实例中传入 printf 的为一个 20 位的数据 0xFFFFF，经过编译后是作为 32 位数据 0x000FFFFF 传入的，由于只支持最大 16 位，printf把高16位的数据作为 %d 的值，所以最终打印的数据为
 15  
如果是如下语句
 	//0xEC78 为 TIM_calculateValue(5000, TIM_mode_1) 的结果  	printf_small("%d\r\n",(uint16_t)0xEC78);
 
编译结果为
 	mov	a,#0x78 	push	acc 	mov	a,#0xec 	push	acc ;注意这边只push了16位（2个acc） 	mov	a,#___str_1 	push	acc 	mov	a,#(___str_1 &gt;&gt; 8) 	push	acc 	mov	a,#0x80 	push	acc 	lcall	_printf_small 	mov	a,sp 	add	a,#0xfb 	mov	sp,a
 
16的值（0xEC78）最高位为 1，打印结果为
 -5000  
所以要打印结果的话，可以使用 printf("%u",...) （占用空间较大） 或者直接传送16位数据到电脑

**Comment by zsiothsu** [comment]
之后可以试试，不过可能有点困难
