### ISSUE TITLE
[Feature] PlatformIO support

### ISSUE THREAD

**Issue by IOsetting** [MCU-ZHISHAN-IoT/HML_FwLib_STC89#6]
Because `.h` files are not in the default folder, when using HML_FwLib_STC89 as a library in PlatformIO project, the header files cannot be recognized automatically.  This can be solved by adding a `library.json` according to https://docs.platformio.org/en/latest/librarymanager/config.html 

I am wondering if it is feasible to add a `library.json` in the root path, which will bring much convenience for PlatformIO users.  
The content of `library.json` could be
```json
{
    "name": "HML_FwLib_STC89",
    "version": "1.3.1",
    "build": {
        "srcDir": "src",
        "includeDir": "inc"
    }
}
```
And for supressing the hint errors in VSCode editor, `linit.h` can be included in stc89.h as well
```c
#ifndef ___HML_STC89_H___
#define ___HML_STC89_H___

#include <lint.h> // Add this line
#include <8051.h>
```

Thanks,

**Comment by zsiothsu** [comment]
Thanks for your feedback, HML will support PlatformIO.
